from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()
ws = wb.active
ws.title = "system_testing"

ws.merge_cells('A1:J1')
ws['A1'] = "System Testing [Template]"
ws['A1'].font = Font(name='Arial', size=18, bold=True)

info = [
    (3, "Project Name", "Employee Attrition Risk Prediction System"),
    (4, "Test Case Author", "Chenu"),
    (5, "Test Case Version", "1.0"),
    (6, "Test Execution Date", "2026-04-10"),
]
for row, label, val in info:
    ws.cell(row=row, column=1, value=label).font = Font(name='Arial', size=11, bold=True)
    ws.cell(row=row, column=2, value=val).font = Font(name='Arial', size=11)

headers = [
    "Functional Requirement No/Ref", "Test Case ID", "Testcase Objective",
    "Testcase Description", "Pre-requisits", "Input Data",
    "Expected Results", "Actual Results", "Execution Status", "Notes"
]
hdr_fill = PatternFill('solid', fgColor='003366')
hdr_font = Font(name='Arial', size=10, bold=True, color='FFFFFF')
hdr_align = Alignment(horizontal='center', vertical='center', wrap_text=True)

for col, h in enumerate(headers, 1):
    c = ws.cell(row=8, column=col, value=h)
    c.font = hdr_font
    c.fill = hdr_fill
    c.alignment = hdr_align

data = [
    ["FR01", "FR01/1", "Verify login with valid credentials",
     "Go to login page, enter valid username and password, click Login",
     "Flask server running; MySQL users table has admin user",
     "Username: admin, Password: admin123",
     "Dashboard page loads successfully with employee table",
     "Dashboard loaded successfully, all panels rendered",
     "Pass", "Response time ~647ms"],

    ["FR01", "FR01/2", "Verify login with invalid credentials",
     "Go to login page, enter wrong password, click Login",
     "Flask server running; MySQL users table has admin user",
     "Username: admin, Password: wrongpass",
     "Error message displayed, user stays on login page",
     "Invalid credentials error shown, login page remains",
     "Pass", "bcrypt hash comparison rejects wrong password"],

    ["FR02", "FR02/1", "Verify survey stress data feeds into risk prediction",
     "Navigate to dashboard, click an employee row, verify stress data from survey_responses is used in risk calculation",
     "Flask server running; MySQL database populated with survey_responses",
     "Employee ID: 1",
     "build_features() aggregates avg_stress_level from survey_responses per employee",
     "Stress level data correctly aggregated and used in prediction",
     "Pass", "Verified via /api/risk/1 JSON response"],

    ["FR02", "FR02/2", "Verify attendance hours data feeds into prediction",
     "Navigate to dashboard, click an employee row, verify hours_worked from attendance_logs is used",
     "Flask server running; MySQL database populated with attendance_logs",
     "Employee ID: 1",
     "build_features() aggregates avg_hours_worked from attendance_logs per employee",
     "Hours worked data correctly aggregated and used in prediction",
     "Pass", "Verified via /api/risk/1 JSON response"],

    ["FR03", "FR03/1", "Verify risk label is returned from API",
     "Send GET request to /api/risk/1, check JSON response contains risk_label field",
     "Flask server running; model loaded at startup",
     "Employee ID: 1",
     "JSON response contains risk_label with value High or Low",
     "JSON response returned with risk_label: High",
     "Pass", "Response time ~120ms"],

    ["FR03", "FR03/2", "Verify confidence percentage is returned",
     "Send GET request to /api/risk/1, check JSON response contains confidence field",
     "Flask server running; model loaded at startup",
     "Employee ID: 1",
     "JSON response contains confidence value between 0-100",
     "JSON response returned with confidence: 78.4",
     "Pass", "Confidence derived from predict_proba"],

    ["FR04", "FR04/1", "Verify SHAP factor chips display in detail drawer",
     "Click an employee row in the dashboard table, check that the slide-out drawer shows negative and positive factor chips",
     "Flask server running; SHAP explainer initialised",
     "Click on Employee row (ID: 1)",
     "Negative factors (red chips) and positive factors (green chips) displayed in drawer",
     "Factor chips displayed correctly with colour coding",
     "Pass", "SHAP TreeExplainer values mapped to features"],

    ["FR04", "FR04/2", "Verify recommended actions render for flagged employee",
     "Click a high-risk employee row, check that numbered action items appear below the factor chips",
     "Flask server running; employee with High risk exists",
     "Click on high-risk Employee row",
     "Numbered action items displayed below factor chips",
     "Recommended actions rendered as numbered list",
     "Pass", "Actions generated by generate_risk_report()"],

    ["FR05", "FR05/1", "Verify clicking employee row opens detailed risk report",
     "Click any employee row in the dashboard table, verify slide-out drawer opens with interpretation and factors",
     "Flask server running; employee table loaded",
     "Click on Employee row (ID: 45)",
     "Drawer opens showing interpretation text, factor chips, and recommended actions",
     "Drawer opened with full risk report",
     "Pass", "Drawer uses CSS transition animation"],

    ["FR05", "FR05/2", "Verify stat cards load correctly",
     "Navigate to dashboard, verify all four stat cards render with correct data",
     "Flask server running; /api/employees endpoint returning data",
     "Navigate to dashboard URL",
     "Four stat cards: Total Employees, High Risk, Low Risk, High Risk Rate",
     "All four stat cards rendered with correct values",
     "Pass", "Data sourced from /api/employees response"],

    ["FR05", "FR05/3", "Verify department risk breakdown chart renders",
     "Navigate to dashboard, verify Chart.js bar chart displays all 6 departments",
     "Flask server running; employee data loaded",
     "Navigate to dashboard URL",
     "Bar chart showing High vs Low risk for IT, HR, Finance, Operations, Sales, Marketing",
     "Bar chart rendered with all 6 departments",
     "Pass", "Chart.js 4.4.0 bar chart"],

    ["FR05", "FR05/4", "Verify model metrics panel shows all five metrics",
     "Navigate to dashboard, verify model performance panel displays all metrics",
     "Flask server running; /api/metrics endpoint returning data",
     "Navigate to dashboard URL",
     "Accuracy, Precision, Recall, F1-Score, AUC-ROC shown with progress bars",
     "All five metrics displayed: 80.2%, 73.7%, 53.2%, 61.8%, 90.4%",
     "Pass", "Metrics loaded from model_metrics.json"],

    ["FR05", "FR05/5", "Verify search and filter functionality",
     "Type in search box, select department dropdown, select risk level sort",
     "Flask server running; employee table loaded",
     'Search: "IT"; Department: Operations; Risk: High',
     "Table filters and re-renders showing only matching employees",
     "Table correctly filtered for each combination",
     "Pass", "Debounced search with 220ms delay"],

    ["FR06", "FR06/1", "Verify employee-facing personalised recommendations view",
     "Attempt to access employee-facing recommendation feature",
     "N/A", "N/A",
     "Employee can view personalised well-being recommendations",
     "Feature not implemented - system is admin-only",
     "N/A - Not Implemented", "FR06 scoped as Could Have; deferred to future"],

    ["FR07", "FR07/1", "Verify external HR system integration",
     "Attempt to integrate with external HR system or dataset",
     "N/A", "N/A",
     "System integrates with external HR systems",
     "Feature not implemented",
     "N/A - Not Implemented", "FR07 scoped as Could Have; deferred to future"],

    ["FR08", "FR08/1", "Verify PII anonymisation enforcement",
     "Check system for storage of personally identifiable information",
     "N/A", "N/A",
     "System does not store or display PII",
     "System uses employee_id integers only, no names stored",
     "Pass", "No PII in database schema"],
]

thin = Side(style='thin', color='000000')
border = Border(left=thin, right=thin, top=thin, bottom=thin)
med = Side(style='medium', color='000000')
light_blue = PatternFill('solid', fgColor='DCE6F1')
white_fill = PatternFill('solid', fgColor='FFFFFF')
pass_fill = PatternFill('solid', fgColor='C6EFCE')
pass_font = Font(name='Arial', size=10, color='006100')
na_fill = PatternFill('solid', fgColor='FFFFCC')
na_font = Font(name='Arial', size=10, color='9C6500')
data_font = Font(name='Arial', size=10)
wrap = Alignment(vertical='top', wrap_text=True)

for i, row_data in enumerate(data):
    row_num = 9 + i
    bg = light_blue if i % 2 == 0 else white_fill
    for col, val in enumerate(row_data, 1):
        c = ws.cell(row=row_num, column=col, value=val)
        c.font = data_font
        c.fill = bg
        c.alignment = wrap
        c.border = border
        if col == 9:
            if val == "Pass":
                c.fill = pass_fill
                c.font = pass_font
            elif "N/A" in str(val):
                c.fill = na_fill
                c.font = na_font

for col in range(1, 11):
    c = ws.cell(row=8, column=col)
    c.border = Border(left=thin, right=thin, top=thin, bottom=med)

widths = [20, 12, 38, 52, 38, 28, 42, 42, 20, 38]
for i, w in enumerate(widths):
    ws.column_dimensions[get_column_letter(i+1)].width = w

ws.freeze_panes = 'A9'
for r in range(9, 25):
    ws.row_dimensions[r].height = 50
ws.row_dimensions[8].height = 35

wb.save(r'C:\Users\Chenu\Desktop\fyp31\system_testing_filled.xlsx')
print("DONE - saved to system_testing_filled.xlsx")
